<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        /* 
            同时请求A B C，完成以后告诉我们
        */
        const p1 = new Promise((resolve, reject) => {
            try {
                console.log("开始请求A数据。。。。");
                // throw new Error("A数据出错？？？？");
                setTimeout(() => {
                    console.log("A请求成功");
                    //假设请求回来的数据A
                    const dataA = {
                        name: "laonie"
                    }
                    resolve(dataA);
                }, 1000)
            } catch (e) {
                reject(e);
            }
        })

        const p2 = new Promise((resolve, reject) => {
            try {
                console.log("开始请求B数据。。。。");
                // throw new Error("B数据出错？？？？");
                setTimeout(() => {
                    console.log("B请求成功");
                    //假设请求回来的数据B
                    const dataB = {
                        age: 18
                    }
                    resolve(dataB)
                }, 2000)
            } catch (e) {
                reject(e);
            }
        })

        const p3 = new Promise((resolve, reject) => {
            try {
                console.log("开始请求C数据。。。。");
                // throw new Error("C数据出错？？？？");
                setTimeout(() => {
                    console.log("C请求成功");
                    //假设请求回来的数据C
                    const dataC = {
                        sex: "nan"
                    }
                    resolve(dataC)
                }, 1500)
            } catch (e) {
                reject(e);
            }
        })


        /* 
            Promise.all():
                - 接受一个数组，数组中放入需要处理的promise实例
                - 当所有的promise实例全部执行成功的时候，all方法返回成功的promise实例，值为内部所有promise实例的成功值组成的数组
                - 当all方法中有任何一个promise实例出现失败，则all方法直接返回失败，值为内部失败promise实例的值

        
        */
        const re = Promise.all([p1, p2, p3]);
        console.log("re", re);

        re.then(value => {
                console.log("所有promise成功，值为", value);
            })
            .catch(reason => {
                console.log("至少有一个promise实例失败，失败信息是", reason);
            })
    </script>
</body>

</html>